### ISSUE TITLE
OTL public requirements tracking issue

### ISSUE THREAD

**Issue by 1024bees** [silogy-io/smelt#24]
This is a list of small and large changes to otl, that I would like to have done before we go public with it.

- [x] Remove otl-controller  done with #23 
- [x] move from global -> local semantics for events, done with #23 
- [x] remove dead code, done on the rust side with #23 and #25 
- [x] solidify otl-root semantics (currently the test list expects otl-root to be the directory that the test list exists in, whereas commands expect otl-root to be the directory the test list exists in. we should probably split these out to be two different pieces of data) #26 
- [x] invalid command list handling 
    - [x] two commands with the same name (failure expected) #26 
    - [x] two commands producing the same output (failure expected) #26 
    - [x] command references command that doesnt exist (failure expected, done with #22)
    - [x] command references file that doesnt exist and isn't produced (failure expected, done with #22)
- [x] Add a readme
